### ISSUE TITLE
exit button disappears when in settings sometimes

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [Saltssaumure/xp-discord-theme#15] opened 2023-09-24 17:45 UTC
please fix

**Comment by Saltssaumure** [comment] 2023-09-25 00:55
Can you clarify if it's a specific page or action in settings that causes the button to disappear? Include screenshots if possible, it'll help me find the cause.

**Comment by Saltssaumure** [comment] 2023-10-14 01:15
Closing for now since I cannot replicate this. Feel free to reopen or reissue if you have more details.

**Closed by Saltssaumure** 2023-10-14 01:15 UTC
